#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generates src/emoji_table.h from Unicode's emoji-data.txt.

    tools/gen_emoji_table.py [/usr/share/unicode/emoji/emoji-data.txt] > src/emoji_table.h

Two range tables, both sorted:
  - kk_emoji_pict: code points that are an emoji on their own (shown in
    colour even without U+FE0F): Emoji_Presentation, every
    Extended_Pictographic from U+1F000 on (which covers code points reserved
    for future emoji), and the Emoji in Misc Symbols / Dingbats (hearts,
    stars, hands people type as text, like U+2764).
  - kk_emoji_any: every Emoji or Extended_Pictographic code point; these
    count only when followed by U+FE0F (e.g. U+00A9 or U+2122 stay text).
"""
import sys

path = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/unicode/emoji/emoji-data.txt"
props = {}
version = "?"
for line in open(path, encoding="utf-8"):
    if line.startswith("# emoji-data") and "-" in line:
        version = line.split("-")[-1].strip().removesuffix(".txt")
    line = line.split("#", 1)[0].strip()
    if not line:
        continue
    cps, prop = (s.strip() for s in line.split(";"))
    lo, _, hi = cps.partition("..")
    lo = int(lo, 16)
    hi = int(hi, 16) if hi else lo
    props.setdefault(prop, set()).update(range(lo, hi + 1))

emoji = props["Emoji"]
ext = props["Extended_Pictographic"]
pres = props["Emoji_Presentation"]
# Digits, # and * are Emoji only as keycaps (handled in emoji.c).
keycap = set(map(ord, "#*0123456789"))
pict = (pres | {c for c in ext if c >= 0x1F000} |
        {c for c in emoji if 0x2600 <= c <= 0x27BF}) - keycap
anyset = (emoji | ext) - keycap


def ranges(s):
    out = []
    for c in sorted(s):
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


def table(name, s):
    rs = ranges(s)
    print(f"static const kk_cp_range {name}[{len(rs)}] = {{")
    for i in range(0, len(rs), 4):
        print("    " + " ".join(f"{{0x{a:X}, 0x{b:X}}}," for a, b in rs[i:i + 4]))
    print("};")


print("/* SPDX-License-Identifier: GPL-3.0-or-later */")
print(f"/* Generated by tools/gen_emoji_table.py from emoji-data.txt {version}.")
print(" * Do not edit by hand. */")
print("#ifndef KK_EMOJI_TABLE_H\n#define KK_EMOJI_TABLE_H\n")
print("typedef struct {\n    unsigned lo, hi;\n} kk_cp_range;\n")
table("kk_emoji_pict", pict)
print()
table("kk_emoji_any", anyset)
print("\n#endif")
